
import '../globals.css'

export const metadata = {
  title: 'Inicio de Sesión',
  description: 'Generated by create next app',
}

export default function SimpleLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  )
}
